DROP TABLE CM_MA_USER_COURSE

CREATE TABLE CM_MA_USER_COURSE (user_course_id  INT(11) NOT NULL AUTO_INCREMENT,USER_CID INT(11) NOT NULL,
COURSE_CID INT(11) NOT NULL,OPRTNL_FLAG CHAR(1) DEFAULT 'A',
CONSTRAINT user_course_id_pk PRIMARY KEY (`user_course_id`),
CONSTRAINT `USER_ID_FK` FOREIGN KEY (`USER_CID`) REFERENCES `user_account` (`id`),
CONSTRAINT `COURSE_ID_FK` FOREIGN KEY (`COURSE_CID`) REFERENCES `CM_MA_COURSE` (`COURSE_ID`))
ENGINE=INNODB AUTO_INCREMENT=100 DEFAULT CHARSET=latin1;
